apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: azure-keyvault-secrets
  namespace: employee-management


spec:

  provider: azure


  secretObjects:

  - secretName: employee-db-secret
    type: Opaque

    data:
    - objectName: DB-USER
      key: DB-USER

    - objectName: DB-PASSWORD
      key: DB-PASSWORD

    - objectName: DB-NAME
      key: DB-NAME

    - objectName: MYSQL-ROOT-PASSWORD
      key: MYSQL-ROOT-PASSWORD


  parameters:

    usePodIdentity: "false"

    useVMManagedIdentity: "true"

    userAssignedIdentityID: "2ac10a9f-291d-4b3f-bf10-a66d4c0fe88f"

    keyvaultName: employee-mgmt-kv-001

    tenantId: a7df9323-95a7-45db-baf0-b676f66238f9

    objects: |
      array:
        - |
          objectName: DB-USER
          objectType: secret
        - |
          objectName: DB-PASSWORD
          objectType: secret
        - |
          objectName: DB-NAME
          objectType: secret
        - |
          objectName: MYSQL-ROOT-PASSWORD
          objectType: secret