apiVersion: v1
kind: Pod

metadata:
  name: keyvault-test-pod
  namespace: employee-management

spec:

  containers:

  - name: nginx
    image: nginx:latest

    volumeMounts:
    - name: secrets-store
      mountPath: "/mnt/secrets-store"
      readOnly: true


  volumes:

  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io

      readOnly: true

      volumeAttributes:
        secretProviderClass: azure-keyvault-secrets
